name: weather
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.1
  shared_preferences: ^2.0.13
  connectivity_plus: ^2.2.1
  flutter_bloc: ^8.0.1
  auto_route: ^3.2.4
  freezed_annotation: ^1.1.0
  dio: ^4.0.4
  get_it: ^7.2.0 
  geolocator: ^8.2.0

  # firebase
  # firebase_core: ^1.13.1
  # firebase_auth: ^3.3.10


dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^1.0.4

  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  auto_route_generator: ^3.2.3


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/


flutter_intl:                                
  enabled: true                              
  class_name: I10n                           
  main_locale: en                            
  arb_dir: lib/core/localization/l10n        
  output_dir: lib/core/localization/generated


flutter_native_splash:
  color: "#343434"
  image: "assets/images/logo.png"
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
